### ISSUE TITLE
X-Carriage rod holes do not line up

### ISSUE THREAD

**Issue by MikeRatcliffe** [gregsaun/bear_extruder_and_x_axis#14]
Note that this was not fixed by commit 21bc1fd85a458e9ea51c5ea404bc7ce8f9eb3d0b

Parts:
- x_carriage_back.stl
- x_carriage.stl

It is obvious from the image that the X-Carriage rod holes do not line up... well, they do but the shells don't.

<img width="171" alt="screen shot 2018-09-17 at 14 43 28" src="https://user-images.githubusercontent.com/116941/45628867-ef6ebd80-ba8c-11e8-9d04-5a313c87ee3a.png">

**Comment by gregsaun** [comment]
This took me some time to understand what was going on here but it is due to the fact that the thickness of the x carriage back is not the same everywhere (on purpose). A correct measurement shows that everything is correctly aligned :
![bear_extruder_bearing_alignment_01](https://user-images.githubusercontent.com/12335098/45804421-51f9d080-bcbc-11e8-89d0-70cb0b60da92.jpg)
